### PR TITLE
Release/0.4.1

### PR DESCRIPTION
**Pull request by fblundun**

### CODE REVIEW

**Comment by fblundun** [comment]
@alexanderdean now that Travis is passing, could you publish 0.4.1-rc1 please?

**Comment by alexanderdean** [comment]
CI/CD bot says:

> Build started!

**Comment by alexanderdean** [comment]
CI/CD bot says:

> Artifact uploaded! https://bintray.com/artifact/download/snowplow/snowplow-generic/kinesis_s3_0.4.1_rc1.zip

**Comment by jbeemster** [comment]
Hey @fblundun @alexanderdean this has been running well for a while.  I believe it can be merged and closed now.  Unless automated CI/CD needs to be added?

**Comment by alexanderdean** [comment]
Awesome - can one of your guys finalize the versions and CHANGELOG and I'll do a manual publish...

**Comment by fblundun** [comment]
Sure - I will do so now...

**Comment by jbeemster** [comment]
@alexanderdean that should do it!

**Pull request merged**
