### PR TITLE
Add support for the Chinese Kinesis endpoint

### PR DESCRIPTION
**Pull request by bobshaw1912**
Adding the endpoint to support AWS China region.

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: **Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.**

Once you've signed, please reply here (e.g. `I signed it!`) and we'll verify. Thanks.

**Comment by jbeemster** [comment]
PR looks good, just waiting for the CLA to be signed.

**Comment by bobshaw1912** [comment]
I signed it!

**Comment by snowplowcla** [comment]
Confirmed! @bobshaw1912 has signed the Individual Contributor License Agreement. Thanks so much.

**Comment by bobshaw1912** [comment]
I signed it!

**Comment by bobshaw1912** [comment]
I've signed the CLA and replied the email already. Anything else to do?

Get Outlook for iOS




On Tue, Oct 25, 2016 at 5:25 PM +0800, "Josh" <notifications@github.com> wrote:












PR looks good, just waiting for the CLA to be signed.

**Pull request closed without merging**
